spring:
  application:
    name: service-problemcenter
  ## 选择运行环境
  profiles:
    active: dev

## 公共配置 ##
server:
  port: 8764
  servlet:
    context-path: /problemcenter
#feign 的超时时间
feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 20000

# cache 配置
cache:
  millisecond: 7200000
key:
  secretKey: ok1293983411faasdf
# log 配置
logging:
  level:
    root: info
    com.kelab.problemcenter.dal.dao: debug
  file: ./logs/problemcenter.log

# mybatis 扫描路径
mybatis:
  mapper-locations: classpath:mapper/*.xml